debug: true

server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cqk?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:

    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
          ddl-autho: update